### ISSUE TITLE
Changes to disabled and hidden properties on cosmoz-tab are not forwarded to paper-tab

### ISSUE THREAD

**Issue by megheaiulian** [Neovici/cosmoz-tabs#19]
The `dom-repeat` element doesn't seem to update changes to properties inside the array passed as `items`.

**Comment by nomego** [comment]
This is usually the case when binding one-way (`[[ items ]]`), try two-way (`{{ items }}`).
Otherwise we might have to add an observer somewhere.. it might also be the `suppressBindingNotifications` if it works in demo but not in frontend.
