### ISSUE TITLE
Re-evaluate URL params when tab states change

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-tabs#35]
Views that has tabs that dynamically disable / hide / activate / show / exist themselves are causing problems with persisted view states in URL since the hash-param URL/state sync carries out before all XHRs and dependant async results are ready to finalize tab states.
What happens now is that cosmoz-tabs falls back to fallbackSelection before the tab has been activated, updating the URL params, creating a new view state.

I propose that the fallback mechanism *does not* update the URL params, to maintain the view state in the URL, even when the tab is not available.
This would fix the issue where we have a data-nav with multiple instances where some instances might not have the tab requested at all, but switching to the next item will correctly choose it as expected.

We would also start reacting to tab state changes, such as tabs being created, enabled or un-hidden. When such a change occurs, and the intended tab (according to URL params) gets activated, we switch to it. This would then in turn solve the issue where the intended tabs gets activated late.

@plequang objections?

**Comment by plequang** [comment]
Seems there is still a problem in Polymer 2.x

**Comment by megheaiulian** [comment]
In 2.x this doesn't work properly and every cosmoz-tabs resets to fallback-selection.
