### ISSUE TITLE
cosmoz-tab full mobile space

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-tabs#42]
![screenshot from 2018-03-29 09-51-36](https://user-images.githubusercontent.com/960553/38076933-7c5fd860-3337-11e8-8b77-619fd44cc92a.png)

cosmoz-tab doesn't fill all available space allocated by cosmoz-tabs in mobile mode.
See white space on bottom

**Comment by programmer4web** [comment]
@nomego cosmoz-tabs need to have explicit size, maybe this is missing in that case? ( I have tested on demo: "explicitly sized cosmoz-tabs with flex iron-list explicitly sizes iron-list" and seems to work as expected in chrome emulated mobile. )

**Comment by megheaiulian** [comment]
This issue no longer makes sense. Implementation changed ....
