### ISSUE TITLE
replace paper-badge

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-tabs#43]
Paper-badge needs resize events to position itself and can't handle displaying more than 2 characters.
We currently use it to display numbers up to 2000 which doesn't work.
These kind of badges usually print things like "9+" for high numbers but I don't think we want that?

**Comment by sanlifer** [comment]
Can't find any replacements but we probably need a badge that can be resized to a sort of pill shape as the numbers increase, and not use the "9+" solution.

Possible to find a replacement?

**Comment by sanlifer** [comment]
We probably need a replacement that can be resized to a pill shape as the counter increases.

Possible to find one?

**Comment by sanlifer** [comment]
Or - it could possibly be solved with CSS according to @nomego

**Comment by megheaiulian** [comment]
I think a `CSS` only solution without an additional component would be the best approach here.
Since we do that I think `iron-collapse` should also be replaced with a simple CSS transition and a `transitionend` event.
