### ISSUE TITLE
cosmoz-tab without name="<name>" displays no content

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-tabs#63]
`cosmoz-tab` elements that are missing the `name="<name>"` attribute show no content.

This error was reproducible in the frontend repository, just by removing the name attribute from a `cosmoz-tab` located within a `<cosmoz-tabs>` element.

Expected behavior: That the tab shows the content without the need of the `name` attribute.
Actual behavior: The content in the tab gets hidden in some way.

**Comment by megheaiulian** [comment]
@dotpointer I don't we should support cosmoz-tab elements without a `name`. We can consider this a developer mistake and assume all tabs that need to function correctly have name. If you agree we can close this ...

**Comment by dotpointer** [comment]
Closing it then.

**Comment by dotpointer** [comment]
Some warning that there are tabs without names should maybe be issued in the console.
