### ISSUE TITLE
On iPhone cosmoz-tabs stays as tabs and doesn't switch to accordion

### ISSUE THREAD

**Issue by cristinecula** [Neovici/cosmoz-tabs#69]

**Comment by cristinecula** [comment]
This is caused by https://github.com/Neovici/cosmoz-viewinfo/issues/14, because at page load `<cosmoz-viewinfo>` `_updateViewSize` has never run and it does not know that it's at mobile size.

**Comment by cristinecula** [comment]
This will by fixed when https://github.com/Neovici/cosmoz-viewinfo/pull/15 is merged.

**Comment by nomego** [comment]
Can someone from testing with iPhone, @SimonThunborg @MickeBerggren @fredrikbernholm confirm this is solved?

**Comment by fredrikbernholm** [comment]
Switches instantly to accordion in 3.7.9 on iPhone, so the issue seems solved.
