### ISSUE TITLE
Specifiying a value for the hash-param does not work on first load

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-tabs#8]
# Description

The demo named "The hashParam attribute binds selected tab to a location hash param" is configured to bind the selected tab to a hash param in the url named `tab`.

When clicking on different tab, one can see the url being updated with the expected parameter, i.e. when clicking on 3rd tab, the url looks like:
http://127.0.0.1:8081/components/cosmoz-tabs/demo/##tab=2 

Also, changing the url updates the selected tab.

However, opening directly the url above (or reloading the page with that url) does not select the third tab, but the second one ("Tab2").

I also tried to remove the `selected=1` attribute in the demo:
```
<cosmoz-tabs _route-hash="{{ hash }}" hash-param="tab">
```
In that case, no tab is selected.

# Expected behavior

When opening http://127.0.0.1:8081/components/cosmoz-tabs/demo/##tab=2, the third tab should be opened.

**Comment by megheaiulian** [comment]
@plequang  This is fixed in the referenced PR.
